name: image
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'
  #     - 'release*'

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  push-init-kyverno:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-initContainer
      digest_command: docker-get-initContainer-digest
      image_name: kyvernopre
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-kyverno
      digest_command: docker-get-kyverno-digest
      image_name: kyverno
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno-cli:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-cli
      digest_command: docker-get-cli-digest
      image_name: kyverno-cli
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  get-digest:
    outputs:
      init-kyverno-image-base64digest: ${{ steps.set-init-kyverno-digest.outputs.digest }}
      kyverno-image-base64digest: ${{ steps.set-kyverno-digest.outputs.digest }}
      kyverno-cli-image-base64digest: ${{ steps.set-cli-digest.outputs.digest }}
    steps:
      - name: get init kyverno image digest
        id: set-init-kyverno-digest
        run: |
          echo "digest is: $(make docker-get-initContainer-sha256sum-digest)"
          echo "::set-output name=digest::$(make docker-get-initContainer-sha256sum-digest | base64 -w0)"
          echo "BASE64 digest is $(make docker-get-initContainer-sha256sum-digest | base64 -w0)"
      - name: get kyverno image digest
        id: set-kyverno-digest
        run: |
          echo "digest is: $(make docker-get-kyverno-sha256sum-digest)"
          echo "::set-output name=digest::$(make docker-get-kyverno-sha256sum-digest | base64 -w0)"
          echo "BASE64 digest is $(make docker-get-kyverno-sha256sum-digest | base64 -w0)"
      - name: get cli image digest
        id: set-cli-digest
        run: |
          echo "digest is: $(make docker-get-cli-sha256sum-digest)"
          echo "::set-output name=digest::$(make docker-get-cli-sha256sum-digest | base64 -w0)"
          echo "BASE64 digest is $(make docker-get-cli-sha256sum-digest | base64 -w0)"
    generate-provenance:
      permissions:
        id-token: write # To sign the provenance.
        contents: write # To upload assets to release.
        actions: read #To read the workflow path.
      # needs: args
      steps:
      - name: init kyverno image provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.1.0
        with:
          base64-subjects: "${{ needs.get-digest.outputs.init-kyverno-image-base64digest }}"
       - name: kyverno image provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.1.0
        with:
          base64-subjects: "${{ needs.get-digest.outputs.kyverno-image-base64digest }}"
       - name: kyverno cli image provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.1.0
        with:
          base64-subjects: "${{ needs.get-digest.outputs.kyverno-cli-image-base64digest }}"

  
