name: SLSA-Generate-Provenance
on:
  workflow_call:
  inputs:
    digest_command: 
        required: true
        type: string

permissions: read-all

jobs:
  get-digest:
    outputs:
      base64digest: ${{ steps.set-digest.outputs.digest }}
    steps:
      - name: get image digest
          id: set-digest
          run: |
            echo "digest is: $(make ${{inputs.digest_command}})"
            echo "::set-output name=digest::$(make ${{inputs.digest_command}} | base64 -w0)"
            echo "BASE64 digest is $(make ${{inputs.digest_command}} | base64 -w0)"
  generate-provenance:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read #To read the workflow path.
    # needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.1.0
    with:
      base64-subjects: "${{ needs.get-digest.outputs.base64digest }}"
