name: SLSA-go-releaser
on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read #To read the workflow path.
    # needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.1.1
    with:
      go-version: 1.18
